services:
  ec-users-mysql:
    image: mysql:latest
    container_name: ec-users-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    networks:
      - ec-network-01

  ec-carts-mongo:
    image: mongo:latest
    container_name: ec-carts-mongo
    networks:
      - ec-network-01

  ec-products-mongo:
    image: mongo:latest
    container_name: ec-products-mongo
    command: mongod --port 27018
    ports:
      - 27018:27018
    networks:
      - ec-network-01

  ec-sales-mongo:
    image: mongo:latest
    container_name: ec-sales-mongo
    command: mongod --port 27019
    ports:
      - 27019:27019
    networks:
      - ec-network-01

  usersAPI:
    image: devrps/ec-users-api-image:1.0
    container_name: ec-users-api-container
    ports:
      - 8083:8083
    depends_on:
      - ec-users-mysql
      - eureka-server
    networks:
      - ec-network-01

  cartsAPI:
    image: devrps/ec-carts-api-image:1.0
    container_name: ec-carts-api-container
    ports:
      - 8081:8081
    depends_on:
      - ec-carts-mongo
      - usersAPI
      - productsAPI
      - eureka-server
    networks:
      - ec-network-01

  productsAPI:
    image: devrps/ec-products-api-image:1.0
    container_name: ec-products-api-container
    ports:
      - 8082:8082
    depends_on:
      - ec-products-mongo
      - eureka-server
    networks:
      - ec-network-01

  salesAPI:
    image: devrps/ec-sales-api-image:1.0
    container_name: ec-sales-api-container
    ports:
      - 80:80
    depends_on:
      - ec-sales-mongo
      - usersAPI
      - cartsAPI
      - eureka-server
    networks:
      - ec-network-01

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - ec-network-01

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - ec-network-01

  eureka-server:
    image: devrps/ec-eureka-image:1.1
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - ec-network-01

  ec-gateway:
    image: devrps/ec-gateway-image:1.0
    ports:
      - 8080:8080
    container_name: ec-gateway-container
    depends_on:
      - eureka-server
    networks:
      - ec-network-01

networks:
  ec-network-01:
    name: ec-network-01